### PR TITLE
Added new blog post on APP thinning, new feature in iOS 9 with xcode 7.

### PR DESCRIPTION
**Pull request by Karthik-M**
Hi Darshan,

Please find new blog post on App thinning and let me know any changes required.

### CODE REVIEW

**Comment by darcwader** [comment]
do you feel this blog post adds something that apple guide and all the links you provided is missing?

**Comment by Karthik-M** [comment]
Hmm... It does not add anything extra, but I thought to write this as to give kind of overview on what app thinning is.

**Comment by MaheshRS** [comment]
@Karthik-M Do you feel `Bitcode` can be a separate post? 
:+1:

**Comment by Karthik-M** [comment]
@MaheshRS Yes we can have bitcode and ORD as separate post.

**Comment by darcwader** [comment]
this seems too generic @Karthik-M , lets do more indepth articles. examples are NSHipster, NatashaTheRobot, NSBlog the kind of content that does not exist in net yet and we are just helping bridge the gap. 

The reason is that we don't want to be another news site like Mashable, TechCrunch where they just give overview of things which all developers would have known already. Idea is to tell someting from another developers perspective.

here is something for your inspiration : http://nshipster.com/colophon/

**Comment by Karthik-M** [comment]
cool @darcwader , I got it. I will try to write in that now onwards. Thank you.

**Pull request closed without merging**
